---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-22
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-22
  template:
    metadata:
      labels:
        app: ubuntu-22
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        nvidia.com/gpu.product: "NVIDIA-H100-80GB-HBM3"
      containers:
      - name: ubuntu-22
        image: hiroominan/ubuntu-dropbear-22.04:python3.11.5
        imagePullPolicy: Always
        ports:
        - containerPort: 5617
        resources:
          limits:
            nvidia.com/gpu: 1 
            cpu: "4"
            memory: "8Gi"
          requests:
            cpu: "4"
            memory: "8Gi"
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsNonRoot: true
        env:
        - name: USER_SSH_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: ssh-key-secret
              key: id_rsa.pub
        command:
        - /bin/sh
        - -c
        - >
          echo 'export PATH=$PATH:/usr/local/cuda/bin:/usr/local/bin' >> ~/.bashrc &&
          echo "$USER_SSH_PUBLIC_KEY" > $HOME/.ssh/authorized_keys &&
          exec dropbear -E -F -w -g -s -j -k -p 5617 -P ./dropbearPID -r ./dropbear_rsa_host_key
        volumeMounts:
          - name: ssh-storage
            mountPath: /data
      volumes:
      - name: ssh-storage
        persistentVolumeClaim:
          claimName: pvc-ubuntu-22