apiVersion: v1
kind: Secret
metadata:
  name: ssh-key-secret
  labels:
    app: ubuntu-22
stringData:
  id_rsa: |
    -----BEGIN RSA PRIVATE KEY-----
    Key disini
    -----END RSA PRIVATE KEY-----
  id_rsa.pub: |
    ssh-rsa your-keys
  authorized_keys: |
    ssh-rsa your-keys