apiVersion: v1
kind: Service
metadata:
  name: svc-ubuntu-test
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: address-pool
spec:
  type: LoadBalancer
  selector:
    app: ubuntu-22
  ports:
  - port: 5617
    name: ssh
    targetPort: 5617
    protocol: TCP